name: Deploy with Docker Compose
# Name of this run
run-name: ${{ github.actor }} Building and Testing
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip -y
        pip3 install mlflow numpy scikit-learn pytest

    - name: Run unit tests
      run: |
        pytest --verbose app/test_model.py

  build_n_push:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout: will clone Git into the image
      - uses: actions/checkout@v4
      # Execute terminal command.
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          envkey_APP_MODEL_NAME: ${{ secrets.APP_MODEL_NAME }}
          envkey_EXPERIMENT_NAME: ${{ secrets.EXPERIMENT_NAME }}
          file_name: .env
          fail_on_empty: true
          sort_keys: true
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker Compose services
        run: docker-compose -f docker-compose.yml pull

      # Add the "Build and Push" step here
      - name: Build and push Docker images
        run: |
         docker build -t shaficse/ml-ait-st124047:latest .
         docker push     shaficse/ml-ait-st124047:latest

      - name: Up Docker Compose services
        run: docker-compose -f docker-compose.yml up -d

  deploy:
    # environment: Production
    needs: build_n_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.KEY }}
          script: |
            tag=${{ github.ref_name }} docker compose -f /home/st124047/st124047/docker-compose.yml down
            tag=${{ github.ref_name }} docker compose -f /home/st124047/st124047/docker-compose.yml up -d
