name: Transition of Model Staging to Production
on:
    push:
      branches:
        - main
jobs:
    Transition:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Install Python and dependencies
          run: |
            sudo apt-get update
            sudo apt-get install python3 python3-pip -y
            pip3 install mlflow numpy scikit-learn pytest
        
        - name: Run Transition
          run: |
            pytest --verbose app/transition.py